INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'AD        ', N'Andorra', N'Andorran')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'AE        ', N'United Arab Emirates', N'Emirian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'AF        ', N'Afghanistan', N'Afghan')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'AG        ', N'Antigua and Barbuda', N'Antiguans, Barbudans')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'AL        ', N'Albania', N'Albanian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'AM        ', N'Armenia', N'Armenian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'AO        ', N'Angola', N'Angolan')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'AR        ', N'Argentina', N'Argentinean')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'AT        ', N'Austria', N'Austrian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'AU        ', N'Australia', N'Australian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'AZ        ', N'Azerbaijan', N'Azerbaijani')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'BA        ', N'Bosnia and Herzegovina', N'Bosnian, Herzegovinian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'BB        ', N'Barbados', N'Barbadian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'BD        ', N'Bangladesh', N'Bangladeshi')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'BE        ', N'Belgium', N'Belgian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'BF        ', N'Burkina Faso', N'Burkinabe')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'BG        ', N'Bulgaria', N'Bulgarian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'BH        ', N'Bahrain', N'Bahraini')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'BI        ', N'Burundi', N'Burundian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'BJ        ', N'Benin', N'Beninese')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'BN        ', N'Brunei', N'Bruneian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'BO        ', N'Bolivia', N'Bolivian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'BR        ', N'Brazil', N'Brazilian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'BS        ', N'The Bahamas', N'Bahamian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'BT        ', N'Bhutan', N'Bhutanese')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'BW        ', N'Botswana', N'Motswana ('',singular), Batswana ('',plural)')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'BY        ', N'Belarus', N'Belarusian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'BZ        ', N'Belize', N'Belizean')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'CA        ', N'Canada', N'Canadian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'CD        ', N'Congo, Republic of the', N'Congolese')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'CG        ', N'Congo, Democratic Republic of the', N'Congolese')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'CH        ', N'Switzerland', N'Swiss')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'CI        ', N'Cote d''Ivoire', N'Ivorian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'CM        ', N'Cameroon', N'Cameroonian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'CN        ', N'China', N'Chinese')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'CO        ', N'Colombia', N'Colombian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'CR        ', N'Costa Rica', N'Costa Rican')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'CU        ', N'Cuba', N'Cuban')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'CV        ', N'Cape Verde', N'Cape Verdian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'CY        ', N'Cyprus', N'Cypriot')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'CZ        ', N'Czech Republic', N'Czech')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'DE        ', N'Germany', N'German')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'DJ        ', N'Djibouti', N'Djibouti')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'DK        ', N'Denmark', N'Danish')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'DM        ', N'Dominica', N'Dominican')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'DO        ', N'Dominican Republic', N'Dominican')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'DZ        ', N'Algeria', N'Algerian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'EC        ', N'Ecuador', N'Ecuadorean')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'EE        ', N'Estonia', N'Estonian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'EG        ', N'Egypt', N'Egyptian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'ER        ', N'Eritrea', N'Eritrean')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'ES        ', N'Spain', N'Spanish')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'ET        ', N'Ethiopia', N'Ethiopian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'FI        ', N'Finland', N'Finnish')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'FJ        ', N'Fiji', N'Fijian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'FR        ', N'France', N'French')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'GA        ', N'Gabon', N'Gabonese')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'GD        ', N'Grenada', N'Grenadian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'GE        ', N'Georgia', N'Georgian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'GH        ', N'Ghana', N'Ghanaian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'GM        ', N'The Gambia', N'Gambian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'GN        ', N'Guinea', N'Guinean')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'GQ        ', N'Equatorial Guinea', N'Equatorial Guinean')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'GT        ', N'Guatemala', N'Guatemalan')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'GW        ', N'Guinea-Bissau', N'Guinea-Bissauan')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'GY        ', N'Guyana', N'Guyanese')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'HK        ', N'Hong Kong', N'Hong Kong')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'HN        ', N'Honduras', N'Honduran')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'HR        ', N'Croatia', N'Croatian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'HT        ', N'Haiti', N'Haitian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'HU        ', N'Hungary', N'Hungarian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'ID        ', N'Indonesia', N'Indonesian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'IE        ', N'Ireland', N'Irish')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'IL        ', N'Israel', N'Israeli')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'IN        ', N'India', N'Indian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'IQ        ', N'Iraq', N'Iraqi')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'IR        ', N'Iran', N'Iranian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'IS        ', N'Iceland', N'Icelander')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'IT        ', N'Italy', N'Italian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'JM        ', N'Jamaica', N'Jamaican')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'JO        ', N'Jordan', N'Jordanian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'JP        ', N'Japan', N'Japanese')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'KE        ', N'Kenya', N'Kenyan')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'KG        ', N'Kyrgyz Republic', N'Kirghiz')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'KH        ', N'Cambodia', N'Cambodian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'KI        ', N'Kiribati', N'I-Kiribati')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'KM        ', N'Comoros', N'Comoran')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'KN        ', N'Saint Kitts and Nevis', N'Kittian and Nevisian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'KP        ', N'Korea, North', N'North Korean')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'KR        ', N'Korea, South', N'South Korean')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'KW        ', N'Kuwait', N'Kuwaiti')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'KY        ', N'Central African Republic', N'Central African')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'KZ        ', N'Kazakhstan', N'Kazakhstani')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'LA        ', N'Laos', N'Laotian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'LB        ', N'Lebanon', N'Lebanese')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'LC        ', N'Saint Lucia', N'Saint Lucian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'LI        ', N'Liechtenstein', N'Liechtensteiner')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'LK        ', N'Sri Lanka', N'Sri Lankan')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'LR        ', N'Liberia', N'Liberian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'LS        ', N'Lesotho', N'Mosotho')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'LT        ', N'Lithuania', N'Lithuanian')
GO
print 'Processed 100 total records'
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'LU        ', N'Luxembourg', N'Luxembourger')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'LV        ', N'Latvia', N'Latvian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'LY        ', N'Libya', N'Libyan')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'MA        ', N'Morocco', N'Moroccan')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'MC        ', N'Monaco', N'Monegasque')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'MD        ', N'Moldova', N'Moldovan')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'MG        ', N'Madagascar', N'Malagasy')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'MH        ', N'Marshall Islands', N'Marshallese')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'MI        ', N'Federated States of Micronesia', N'Micronesian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'MK        ', N'Macedonia', N'Macedonian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'ML        ', N'Mali', N'Malian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'MM        ', N'Myanmar ('',Burma)', N'Burmese')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'MR        ', N'Mauritania', N'Mauritanian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'MT        ', N'Malta', N'Maltese')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'MU        ', N'Mauritius', N'Mauritian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'MV        ', N'Maldives', N'Maldivan')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'MW        ', N'Malawi', N'Malawian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'MX        ', N'Mexico', N'Mexican')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'MY        ', N'Malaysia', N'Malaysian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'MZ        ', N'Mozambique', N'Mozambican')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'NA        ', N'Namibia', N'Namibian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'NE        ', N'Niger', N'Nigerien')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'NG        ', N'Nigeria', N'Nigerian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'NI        ', N'Nicaragua', N'Nicaraguan')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'NL        ', N'Netherlands', N'Dutch')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'NO        ', N'Norway', N'Norwegian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'NP        ', N'Nepal', N'Nepalese')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'NR        ', N'Nauru', N'Nauruan')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'NZ        ', N'New Zealand', N'New Zealander')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'OM        ', N'Oman', N'Omani')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'PA        ', N'Panama', N'Panamanian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'PE        ', N'Peru', N'Peruvian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'PG        ', N'Papua New Guinea', N'Papua New Guinean')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'PH        ', N'Philippines', N'Filipino')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'PK        ', N'Pakistan', N'Pakistani')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'PL        ', N'Poland', N'Polish')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'PT        ', N'Portugal', N'Portuguese')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'PW        ', N'Palau', N'Palauan')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'PY        ', N'Paraguay', N'Paraguayan')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'QA        ', N'Qatar', N'Qatari')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'RO        ', N'Romania', N'Romanian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'RS        ', N'Serbia and Montenegro', N'Serbian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'RU        ', N'Russia', N'Russian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'RW        ', N'Rwanda', N'Rwandan')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'SA        ', N'Saudi Arabia', N'Saudi Arabian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'SB        ', N'Solomon Islands', N'Solomon Islander')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'SC        ', N'Seychelles', N'Seychellois')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'SD        ', N'Sudan', N'Sudanese')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'SE        ', N'Sweden', N'Swedish')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'SG        ', N'Singapore', N'Singaporean')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'SI        ', N'Slovenia', N'Slovene')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'SK        ', N'Slovakia', N'Slovak')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'SL        ', N'Sierra Leone', N'Sierra Leonean')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'SM        ', N'San Marino', N'Sammarinese')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'SN        ', N'Senegal', N'Senegalese')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'SO        ', N'Somalia', N'Somali')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'SR        ', N'Suriname', N'Surinamer')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'ST        ', N'Sao Tome and Principe', N'Sao Tomean')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'SV        ', N'El Salvador', N'Salvadoran')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'SY        ', N'Syria', N'Syrian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'SZ        ', N'Swaziland', N'Swazi')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'TD        ', N'Chad', N'Chadian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'TG        ', N'Togo', N'Togolese')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'TH        ', N'Thailand', N'Thai')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'TJ        ', N'Tajikistan', N'Tadzhik')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'TL        ', N'East Timor', N'East Timorese')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'TM        ', N'Turkmenistan', N'Turkmen')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'TN        ', N'Tunisia', N'Tunisian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'TO        ', N'Tonga', N'Tongan')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'TR        ', N'Turkey', N'Turkish')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'TT        ', N'Trinidad and Tobago', N'Trinidadian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'TV        ', N'Tuvalu', N'Tuvaluan')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'TW        ', N'Taiwan', N'Taiwanese')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'TZ        ', N'Tanzania', N'Tanzanian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'UA        ', N'Ukraine', N'Ukrainian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'UG        ', N'Uganda', N'Ugandan')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'UK        ', N'United Kingdom', N'British')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'US        ', N'United States', N'American')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'UY        ', N'Uruguay', N'Uruguayan')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'UZ        ', N'Uzbekistan', N'Uzbekistani')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'VA        ', N'Vatican City ('',Holy See)', N'none')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'VE        ', N'Venezuela', N'Venezuelan')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'VH        ', N'Chile', N'Chilean')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'VN        ', N'Vietnam', N'Vietnamese')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'VU        ', N'Vanuatu', N'Ni-Vanuatu')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'WS        ', N'Samoa', N'Samoan')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'YE        ', N'Yemen', N'Yemeni')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'ZA        ', N'South Africa', N'South African')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'ZM        ', N'Zambia', N'Zambian')
INSERT [dbo].[Countries] ([CountryID], [CountryName], [Nationality]) VALUES (N'ZW        ', N'Zimbabwe', N'Zimbabwean')